package A.F.A;

public enum Provincia {

    BUENOSAIRES,SANTAFE,MENDOZA,JUJUY,SALTA,SANTACRUZ,CORRIENTES,TIERRADELFUEGO,CORDOBA,CHACO,FORMOSA,SANTIAGODELESTERO,ENTRERIOS,LAPAMPA,CATAMARCA,CHUBUT,MISIONES,LARIOJA,RIONEGRO,TUCUMAN,NEUQUEN,SANLUIS
}
